"""Compute and save to disk the lensing power spectra."""

import tempfile
import os
import shutil

import healpy as hp
import numpy as np

from mpi4py.MPI import COMM_WORLD as comm
from healqest import startup, log
from healqest.spectrum import KappaMap, compute_ps, ClsDB

logger = log.get_logger(__name__)


def stype2ktypes(stype):
    k1 = stype[:2]
    k2 = stype[2:]
    if not k2:
        k2 = None
    return k1, k2


def stypes2ktypes(spec_types):
    """Convert 4-letter spec types to non-repeated 2-letter kmap types."""
    ktypes = []
    for stype in spec_types:
        k1, k2 = stype2ktypes(stype)
        ktypes.append(k1)
        ktypes.append(k2)
    return set(ktypes)


def get_kmap_and_spec(config, stypes, i, mvtype, N1, mf_pair, curl=False, cmbset='a', skip=False):
    """
    Prepare the kappa maps for all the spectra, and compute the spectra of given types.

    The result will be broadcasted to rank 0 and written to the database there.

    Parameters
    ----------
    config: Config
    stypes: list of str
        list of 4-letter spec types, e.g., 'xxxx', 'xyyx'
    i: int
        seed number
    mvtype: str
        the lensrec MV type, e.g., "TT", "EB"
    N1: bool
        whether to compute N1-type spectra. if False, compute N0-type spectra.
    mf_pair: tuple of int
        the meanf-field group for the two kappa maps.
    curl: bool
        whether to compute the curl mode spectra.
    cmbset: str='a'
        the CMB set for the sims, e.g., 'a', 'b', '
    skip: bool
        whether to skip the spectra that already exist in the database.
    """
    # validate the single database for this call
    db = None
    to_skip = list()

    for stype in stypes:
        k1, k2 = stype2ktypes(stype)
        db_new, sql_key = config.get_sql_keys(
            tag=mvtype, seed=i, ktype1=k1, ktype2=k2, N1=N1, SAN0=False, cmbset=cmbset, curl=curl
        )
        if db is None:
            db = db_new
        else:
            assert db == db_new, "all specs in the same call should write to the same SQLite table."
        if skip:
            if db.query(sql_key, return_data=False):
                spec_key = '_'.join(sql_key.values())
                logger.info(f"skipping {db.name} {db.table}: {spec_key}", extra={'force': True})
                to_skip.append(stype)
    stypes = [s for s in stypes if s not in to_skip]

    with tempfile.TemporaryDirectory(prefix='lens', dir=config.tmp_dir) as tmp:
        kmaps = dict()
        for ktype in stypes2ktypes(stypes):
            for g in set(mf_pair):
                kmaps[(ktype, g)] = KappaMap(
                    config, i, ktype, mvtype=mvtype, mf_group=g, N1=N1, cmbset=cmbset, outdir=tmp, curl=curl
                )

        local_results = []
        for stype in stypes:
            k1, k2 = stype2ktypes(stype)
            g1, g2 = mf_pair
            _, sql_key = config.get_sql_keys(
                tag=mvtype, seed=i, ktype1=k1, ktype2=k2, N1=N1, SAN0=False, cmbset=cmbset, curl=curl
            )
            cl_dat = compute_ps(kmaps[(k1, g1)], kmaps[(k2, g2)])
            local_results.append((sql_key, cl_dat))
        if local_results:
            comm.send((db.path, db.table, local_results), dest=comm.size - 1)


def main(i, mvtype, cmbset, curl=False, skip=False):
    mf_pair = [1, 2] if config.mfsplit else [0, 0]
    common_kw = dict(i=i, mvtype=mvtype, skip=skip, curl=curl, config=config)
    if args.std:
        if i == 0:
            logger.warning(
                'i=0 skipped for N0 set. use `-rdn0` flag to compute the data spectrum.',
                extra={'force': True},
            )
        stypes = [] if i == 0 else ['xxxx', 'xyyx', 'xyxy']
        get_kmap_and_spec(stypes=stypes, N1=False, cmbset=cmbset, mf_pair=mf_pair, **common_kw)
        if args.cross:
            get_kmap_and_spec(stypes=['xx'], N1=False, cmbset=cmbset, mf_pair=(0, 0), **common_kw)

    elif args.rdn0:
        # TODO: `do_bundle` for RDN0 hasn't been implemented (only the data spectrum i==0 has)
        stypes = ['xxxx'] if i == 0 else ['x0x0', 'x00x', '0xx0', '0x0x']
        get_kmap_and_spec(stypes=stypes, N1=False, cmbset=cmbset, mf_pair=mf_pair, **common_kw)

    elif args.n1:
        stypes = [] if i == 0 else ['abba', 'abab', 'xyxy', 'xyyx', 'aabb']
        get_kmap_and_spec(stypes=stypes, N1=True, cmbset='a', mf_pair=mf_pair, **common_kw)
        if args.cross:
            get_kmap_and_spec(stypes=['aa'], N1=True, cmbset='a', mf_pair=(0, 0), **common_kw)


if __name__ == "__main__":
    """
    Compute power spectra of all lensing reconstruction.

    Prerequisites
    -------------
    - lensing reconstruction maps, generated by `rec_lens.py`.
    - meanf-field files generated by `get_plmstack.py`.

    Examples
    --------
    - standard N0-type spectra (i=0 will be ignored)
    >>> $run scripts/compute_cls.py -c $config -f $field -mvtype $mv -i1 1 -i2 $i2 -std [-curl]
    - N1-type spectra (i=0 will be ignored)
    >>> $run scripts/compute_cls.py -c $config -f $field -mvtype $mv -i1 1 -i2 $i2 -n1 [-curl]
    - RDN0-type (and data) spectra (i=0 is data).
    >>> $run scripts/compute_cls.py -c $config -f $field -mvtype $mv -i1 1 -i2 $i2 -rdn0 [-curl]
    """
    parser = startup.parser()
    parser.add_argument('-i1', default=1, type=int, help='seed start')
    parser.add_argument('-i2', default=1, type=int, help='seed stop')
    parser.add_argument('-std', action='store_true', help='do standard Cls')
    parser.add_argument('-rdn0', action='store_true', help='do RDN0-type operations')
    parser.add_argument('-mvtype', default=None, type=str, help='MV type')
    parser.add_argument('-cross', action='store_true', help='compute cross spectra')
    parser.add_argument('-curl', action='store_true', help='compute the curl mode')
    parser.add_argument('-set', default='a', type=str, help='cmbset for std/N0-type sims')
    args = parser.parse_args()
    log.setup_logger(verbose=args.verbose)
    config = startup.Config.from_args(args)

    assert comm.size > 1, f"{__name__} only works in MPI mode."

    config.tmp_dir = config.path(config.outdir, 'tmp/')  # /tmp might be too small for storage
    config.tmp_file_mask = os.path.join(config.tmp_dir, 'psmask.fits')

    if comm.rank == 0:
        os.makedirs(config.tmp_dir, exist_ok=True)
        hp.write_map(config.tmp_file_mask, config.mask_ps, dtype=np.float32, overwrite=True)
    comm.barrier()

    loop = np.arange(args.i1, args.i2 + 1)

    if comm.rank == comm.size - 1:
        ClsDB.mpi_write(comm)
    else:
        for _i in loop[comm.rank :: (comm.size - 1)]:
            main(_i, cmbset=args.set, mvtype=args.mvtype, curl=args.curl, skip=args.skip)
        comm.send(None, dest=comm.size - 1)

    comm.barrier()
    if comm.rank == 0:
        os.unlink(config.tmp_file_mask)
        shutil.rmtree(config.tmp_dir)
