"""Compute and save to disk the lensing power spectra."""

import tempfile
import os
import shutil

import healpy as hp
import numpy as np
from mpi4py.MPI import COMM_WORLD as comm
from healqest import startup, log
from healqest.spectrum import KappaMap, compute_ps

logger = log.get_logger(__name__)


def stype2ktypes(stype):
    k1 = stype[:2]
    k2 = stype[2:]
    if not k2:
        k2 = None
    return k1, k2


def stypes2ktypes(spec_types):
    """Convert 4-letter spec types to non-repeated 2-letter kmap types."""
    ktypes = []
    for stype in spec_types:
        k1, k2 = stype2ktypes(stype)
        ktypes.append(k1)
        ktypes.append(k2)
    return set(ktypes)


def get_kmap_and_spec(config, stypes, i, mvtype, N1, mf_pair, curl=False, cmbset='a', skip=False):
    with tempfile.TemporaryDirectory(prefix='lens', dir=config.tmp_dir) as tmp:
        kmaps = dict()
        for ktype in stypes2ktypes(stypes):
            for g in set(mf_pair):
                kmaps[(ktype, g)] = KappaMap(
                    config, i, ktype, mvtype=mvtype, mf_group=g, N1=N1, cmbset=cmbset, outdir=tmp, curl=curl
                )
        for stype in stypes:
            k1, k2 = stype2ktypes(stype)
            g1, g2 = mf_pair
            compute_ps(kmaps[(k1, g1)], kmaps[(k2, g2)], skip=skip, save=True)


def main(i, mvtype, cmbset, curl=False, skip=False):
    mf_pair = [1, 2] if config.mfsplit else [0, 0]
    common_kw = dict(i=i, mvtype=mvtype, skip=skip, curl=curl, config=config)
    if args.std:
        stypes = [] if i == 0 else ['xxxx', 'xyyx', 'xyxy']
        get_kmap_and_spec(stypes=stypes, N1=False, cmbset=cmbset, mf_pair=mf_pair, **common_kw)
        if args.cross:
            get_kmap_and_spec(stypes=['xx'], N1=False, cmbset=cmbset, mf_pair=(0, 0), **common_kw)

    elif args.rdn0:
        # TODO: `do_bundle` for RDN0 hasn't been implemented (only the data spectrum i==0 has)
        stypes = ['xxxx'] if i == 0 else ['x0x0', 'x00x', '0xx0', '0x0x']
        get_kmap_and_spec(stypes=stypes, N1=False, cmbset=cmbset, mf_pair=mf_pair, **common_kw)

    elif args.n1:
        stypes = [] if i == 0 else ['abba', 'abab', 'xyxy', 'xyyx', 'aabb']
        get_kmap_and_spec(stypes=stypes, N1=True, cmbset='a', mf_pair=mf_pair, **common_kw)
        if args.cross:
            get_kmap_and_spec(stypes=['aa'], N1=True, cmbset='a', mf_pair=(0, 0), **common_kw)


if __name__ == "__main__":
    """
    Compute power spectra of all lensing reconstruction.

    Prerequisites
    -------------
    - lensing reconstruction maps, generated by `rec_lens.py`.
    - meanf-field files generated by `get_plmstack.py`.

    Examples
    --------
    - standard N0-type spectra (i=0 will be ignored)
    >>> $run scripts/compute_cls.py -c $config -f $field -mvtype $mv -i1 1 -i2 $i2 -std [-curl]
    - N1-type spectra (i=0 will be ignored)
    >>> $run scripts/compute_cls.py -c $config -f $field -mvtype $mv -i1 1 -i2 $i2 -n1 [-curl]
    - RDN0-type (and data) spectra (i=0 is data).
    >>> $run scripts/compute_cls.py -c $config -f $field -mvtype $mv -i1 1 -i2 $i2 -rdn0 [-curl]
    """
    parser = startup.parser()
    parser.add_argument('-i1', default=1, type=int, help='seed start')
    parser.add_argument('-i2', default=1, type=int, help='seed stop')
    parser.add_argument('-std', action='store_true', help='do standard Cls')
    parser.add_argument('-rdn0', action='store_true', help='do RDN0-type operations')
    parser.add_argument('-mvtype', default=None, type=str, help='MV type')
    parser.add_argument('-cross', action='store_true', help='compute cross spectra')
    parser.add_argument('-curl', action='store_true', help='compute the curl mode')
    parser.add_argument('-set', default='a', type=str, help='cmbset for std/N0-type sims')
    args = parser.parse_args()
    startup.setup_logger(verbose=args.verbose)
    config = startup.Config.from_args(args)

    config.tmp_dir = config.path(config.outdir, 'tmp/')  # /tmp might be too small for storage
    config.tmp_file_mask = os.path.join(config.tmp_dir, 'psmask.fits')
    if comm.rank == 0:
        os.makedirs(config.tmp_dir, exist_ok=True)
        hp.write_map(config.tmp_file_mask, config.mask_ps, dtype=np.float32, overwrite=True)
    comm.barrier()

    loop = np.arange(args.i1, args.i2 + 1)
    for _i in loop[comm.rank :: comm.size]:
        main(_i, cmbset=args.set, mvtype=args.mvtype, curl=args.curl, skip=args.skip)
    comm.barrier()
    if comm.rank == 0:
        os.unlink(config.tmp_file_mask)
        shutil.rmtree(config.tmp_dir)
