import logging
import numpy as np
import healpy as hp
import os
from healqest import startup, healqest_utils
from itertools import product

try:
    from mpi4py import MPI

    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()
    has_mpi = True
except ImportError:
    rank = 0
    size = 1
    has_mpi = False

logger = logging.getLogger(__name__)


def load(tag, i, ktype, cmbset, N1=False, bundle=None):
    s1, s2, c1, c2 = config.ktype2ij(ktype, i, j=None, cmbset=cmbset)
    if config.save_as_map:
        fname = config.p_plm(tag=tag, seed1=s1, seed2=s2, cmbset1=c1, cmbset2=c2, N1=N1, bundle=bundle)
        out = healqest_utils.read_map(fname, dtype=np.float64, field=(0, 1), return_cosmo=False)
        out = hp.ma(out, badval=0)  # important for partial maps.
        out.fill_value = hp.UNSEEN  # important for partial maps.
        return out
    else:
        fname = config.p_plm(tag=tag, seed1=s1, seed2=s2, cmbset1=c1, cmbset2=c2, N1=N1, bundle=bundle)
        loaded = np.load(fname)
        glm, clm = loaded['glm'], loaded['clm']
        return glm, clm


def main(tag, key, bundle, cmbset):
    ktype = key.split('_')[0]
    N1 = key.split('_')[-1] == "N1"
    if N1 and cmbset != 'a':
        logger.warning(f"N1-type sims only support cmbset 'a', got {cmbset}. Exiting!")
        return

    i1, i2 = config.sim_range_N1 if N1 else config.sim_range
    spl_i = (i1 + i2) // 2  # mf split mid point
    mf1_grad, mf2_grad = 0, 0
    mf1_curl, mf2_curl = 0, 0
    nsim1, nsim2 = 0, 0

    fname = config.p_plm(tag=tag, stack_type=ktype, N1=N1, bundle=bundle, cmbset=cmbset)
    if args.skip and os.path.exists(fname):
        return
    os.makedirs(os.path.dirname(fname), exist_ok=True)

    for i in range(i1, i2 + 1, 1):
        mf_g, mf_c = load(tag, i, ktype, cmbset=cmbset, N1=N1, bundle=bundle)
        if i < spl_i + 1:
            mf1_grad += mf_g
            mf1_curl += mf_c
            nsim1 += 1
        else:
            mf2_grad += mf_g
            mf2_curl += mf_c
            nsim2 += 1

    # write to disk
    mf_grad = mf1_grad + mf2_grad
    mf_curl = mf1_curl + mf2_curl
    if config.save_as_map:
        maps_out = hp.ma([mf_grad, mf1_grad, mf2_grad, mf_curl, mf1_curl, mf2_curl])
        hp.write_map(
            fname,
            maps_out,
            overwrite=True,
            dtype=np.float32,
            partial=True,
            column_names=['gmf', 'gmf1', 'gmf2', 'cmf', 'cmf1', 'cmf2'],
            extra_header=[
                ('NSIM', nsim1 + nsim2, "Number of sims in total"),
                ('NSIM1', nsim1, "Number of sims in MF group 1"),
                ('NSIM2', nsim2, "Number of sims in MF group 2"),
                ('SPLITIDX', spl_i, "Index that splits two MF groups"),
            ],
        )
    else:
        np.savez(
            fname,
            gmf1=mf1_grad,
            gmf2=mf2_grad,
            gmf=mf_grad,
            cmf1=mf1_curl,
            cmf2=mf2_curl,
            cmf=mf_curl,
            nsim1=nsim1,
            nsim2=nsim2,
            nsim=nsim1 + nsim2,
            split_i=spl_i,
        )
    logger.info(f"stacking: {tag}-{key}-{bundle} completed.")


if __name__ == "__main__":
    """
    Stack the (simulated) lensing reconstruction for mean-field estimates.

    Prerequisites
    -------------
    - lensing reconstruction maps, generated by `rec_lens.py`.

    Examples
    --------
    - N0-type stacking.
    >>> $run scripts/get_plmstack.py -c $config -f $field [-set a] -std

    - N1-type stacking. `set` has to be `a` (or omit), the a/b type will be handled internally.
    >>> $run scripts/get_plmstack.py -c $config -f $field -set a -n1

    - RDN0-type stacking.
    $run scripts/get_plmstack.py -c $config -f $field -set a -rdn0
    """
    parser = startup.parser()
    parser.add_argument('-set', default='a', type=str, help='cmbset for std/N0-type sims')
    parser.add_argument('-std', action='store_true', help='do standard Cls')
    parser.add_argument('-rdn0', action='store_true', help='do RDN0-type operations')
    args = parser.parse_args()
    startup.setup_logger(verbose=args.verbose)
    config = startup.Config.from_args(args)

    if config.save_as_map:
        tags = config.mvtypes
    else:
        tags = config.qes

    keys = []
    if args.std:
        keys += ['xx', 'xy', 'yx']
    if args.rdn0:
        keys += ['x0', '0x']
    if args.n1:
        keys += ['xy_N1', 'yx_N1', 'ab_N1', 'ba_N1', 'aa_N1', 'bb_N1']

    if config.nbundle is None or args.bundle is None:
        bundle_pairs = [[None, None]]
    else:
        # do cross-bundle lensrec
        # assuming slurm always distribute "nbundle" jobs to compute all lensrec
        bundle_pairs = np.array_split(config.bundle_pairs, config.nbundle)[::-1][args.bundle]

    loop = list(product(tags, keys, bundle_pairs))

    for _tag, _key, _bundle_pair in loop[rank::size]:
        main(_tag, _key, _bundle_pair, cmbset=args.set)
