import numpy as np
import healpy as hp
import os
from healqest import startup, healqest_utils, log
from itertools import product

try:
    from mpi4py import MPI

    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()
    has_mpi = True
except ImportError:
    rank = 0
    size = 1
    has_mpi = False

logger = log.get_logger(__name__)


def load(tag, i, ktype, cmbset, N1=False, bundle=None):
    s1, s2, c1, c2 = config.ktype2ij(ktype, i, j=None, cmbset=cmbset)

    fname = config.p_plm(tag=tag, seed1=s1, seed2=s2, cmbset1=c1, cmbset2=c2, N1=N1, bundle=bundle)
    field = 0 if config.disable_curl else (0, 1)
    return healqest_utils.read_map(fname, dtype=np.float64, field=field, return_cosmo=False, partial=True)


def accumulate_mean_fields(tag, ktype, cmbset, N1, bundle, i1, i2, split_index, components):
    mean_fields = np.zeros((len(components), 2, len(partial_index)), dtype=np.float64)
    nsims = np.zeros(2, dtype=int)

    for i in range(i1, i2 + 1):
        plms = np.atleast_2d(load(tag, i, ktype, cmbset=cmbset, N1=N1, bundle=bundle))
        half = int(i >= split_index + 1)
        np.add(mean_fields[:, half], plms, out=mean_fields[:, half])
        nsims[half] += 1

    return mean_fields, nsims


def main(tag, key, bundle, cmbset):
    if config.quick and healqest_utils.mv_is_symm(tag) and key in {'yx', 'x0', 'yx_N1', 'ba_N1'}:
        logger.warning(f"quick mode: skipping symmetric stack {tag}-{key}", extra={'force': True})
        return

    ktype = key.split('_')[0]
    N1 = key.split('_')[-1] == "N1"
    if N1 and cmbset != 'a':
        logger.warning(f"N1-type sims only support cmbset 'a', got {cmbset}. Exiting!")
        return

    i1, i2 = config.sim_range_N1 if N1 else config.sim_range
    spl_i = (i1 + i2) // 2  # mf split mid point
    components = ('grad',) if config.disable_curl else ('grad', 'curl')

    fname = config.p_plm(tag=tag, stack_type=ktype, N1=N1, bundle=bundle, cmbset=cmbset)
    if args.skip and os.path.exists(fname):
        return
    os.makedirs(os.path.dirname(fname), exist_ok=True)

    mean_fields, nsims = accumulate_mean_fields(tag, ktype, cmbset, N1, bundle, i1, i2, spl_i, components)

    # write to disk
    maps_out = np.full((3 * len(components), hp.nside2npix(config.nside)), hp.UNSEEN, dtype=np.float32)
    column_names = []
    for component_index, (component, (mf1, mf2)) in enumerate(zip(components, mean_fields)):
        offset = 3 * component_index
        prefix = component[0]
        maps_out[offset, partial_index] = mf1 + mf2
        maps_out[offset + 1, partial_index] = mf1
        maps_out[offset + 2, partial_index] = mf2
        column_names += [f'{prefix}mf', f'{prefix}mf1', f'{prefix}mf2']

    hp.write_map(
        fname,
        maps_out,
        overwrite=True,
        dtype=np.float32,
        partial=True,
        column_names=column_names,
        extra_header=[
            ('NSIM', int(np.sum(nsims)), "Number of sims in total"),
            ('NSIM1', int(nsims[0]), "Number of sims in MF group 1"),
            ('NSIM2', int(nsims[1]), "Number of sims in MF group 2"),
            ('SPLITIDX', spl_i, "Index that splits two MF groups"),
        ],
    )

    logger.info(f"stacking: {tag}-{key}-{bundle} completed.")


if __name__ == "__main__":
    """
    Stack the (simulated) lensing reconstruction for mean-field estimates.

    Prerequisites
    -------------
    - lensing reconstruction maps, generated by `rec_lens.py`.

    Examples
    --------
    - N0-type stacking.
    >>> $run scripts/get_plmstack.py -c $config -f $field [-set a] -std

    - N0-type xx-only stacking.
    >>> $run scripts/get_plmstack.py -c $config -f $field [-set a] -std-xx

    - N1-type stacking. `set` has to be `a` (or omit), the a/b type will be handled internally.
    >>> $run scripts/get_plmstack.py -c $config -f $field -set a -n1

    - RDN0-type stacking.
    $run scripts/get_plmstack.py -c $config -f $field -set a -rdn0
    """
    parser = startup.parser()
    parser.add_argument('-set', default='a', type=str, help='cmbset for std/N0-type sims')
    parser.add_argument('-std', action='store_true', help='do standard Cls')
    parser.add_argument('-std-xx', action='store_true', help='do standard xx stacks only')
    parser.add_argument('-rdn0', action='store_true', help='do RDN0-type operations')
    args = parser.parse_args()
    log.setup_logger(verbose=args.verbose)
    config = startup.Config.from_args(args)
    with np.load(config.p_index) as index_file:
        partial_index = index_file['index']

    tags = config.mvtypes

    keys = []
    if args.std_xx:
        keys += ['xx']
    elif args.std:
        keys += ['xx', 'xy', 'yx']
    if args.rdn0:
        keys += ['x0', '0x']
    if args.n1:
        keys += ['xy_N1', 'yx_N1', 'ab_N1', 'ba_N1', 'aa_N1', 'bb_N1']

    if config.nbundle is None or args.bundle is None:
        bundle_pairs = [[None, None]]
    else:
        # do cross-bundle lensrec
        # assuming slurm always distribute "nbundle" jobs to compute all lensrec
        bundle_pairs = np.array_split(config.bundle_pairs, config.nbundle)[::-1][args.bundle]

    loop = list(product(tags, keys, bundle_pairs))

    for _tag, _key, _bundle_pair in loop[rank::size]:
        main(_tag, _key, _bundle_pair, cmbset=args.set)
